name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'

      - name: Build site
        run: hugo --minify --environment production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "rajatsaxena314"
          user_email: "rajatsaxena314@users.noreply.github.com"
          keep_files: false
      
      - name: Push public to gh-pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"
          git add -f public
          git commit -m "Update gh-pages"
          git push origin `git subtree split --prefix public main`:gh-pages --force